### ISSUE TITLE
spot_cloudspace data resource does not output a working kubeconfig.

### ISSUE THREAD

**Issue by estenrye** [rackerlabs/terraform-provider-spot#4]
# Problem

Kubeconfig output by the terraform provider does not result in a validly formatted or working kubeconfig.

# How to Reproduce

```terraform
terraform {
    backend "s3" {
        region = "us-east-2"
        bucket = "bucket-name"
        key = "rackspace-spot/argocd/terraform.tfstate"
    }

    required_providers {
        onepassword = {
            source = "1Password/onepassword"
            version = "1.4.3"
        }

        spot = {
            source = "rackerlabs/spot"
            version = "0.0.3"
        }
    }
}

provider "onepassword" {
}

# data "onepassword_item" "spot_credentials" {
#   vault = "Home_Lab"
#   title = "Rackspace-SPOT"
# }

provider "spot" {}

resource "spot_cloudspace" "cloudspace" {
  cloudspace_name    = "example"
  region             = "us-central-dfw-1"
  hacontrol_plane    = false
}

resource "spot_spotnodepool" "example" {
  cloudspace_name = "example"
  server_class    = "mh.vs1.2xlarge-dfw"
  bid_price       = 0.03
  autoscaling = {
    min_nodes = 2
    max_nodes = 4
  }
}

data "spot_cloudspace" "cloudspace" {
  id = spot_cloudspace.cloudspace.id
}

resource "local_sensitive_file" "home_kubeconfig" {
  content  = data.spot_cloudspace.cloudspace.kubeconfig
  filename = pathexpand("~/.kube/${data.spot_cloudspace.cloudspace.id}-kubeconfig.yaml")
}
```

Example redacted output of `~/.kube/org-id-redacted/example-kubeconfig.yaml` from the kubeconfig on a first run, before the cloudspace has completed its provisioning.

```yaml
apiVersion: v1
clusters:
- cluster:
        insecure-skip-tls-verify: true
        server: >-
        https:///
name: example
contexts:
- context:
        cluster: example
        namespace: default
        user: ngpc-user
name: rxtspot-example
current-context: rxtspot-example
kind: Config
preferences: {}
users:
- name: ngpc-user
user:
        token: >-
        ey..........MySuperLongTokenStringIRedacted............zg
```
Note that the provider
- does not output the server information.
- does not properly indent the multiline text fields `.users[0].user.token` and `.clusters[0].cluster.server`
- does not properly indent `.users[0].user`
- does not properly indent  `.contexts[0].name`
- does not properly indent `.users[0].user`

Example redacted output of `~/.kube/org-id-redacted/example-kubeconfig.yaml` from the kubeconfig on a first run, 45 minutes later, after the cloudspace had finished provisioning.

```yaml
apiVersion: v1
clusters:
- cluster:
        insecure-skip-tls-verify: true
        server: >-
        https://vcp-REDACTED.cloud-REDACTED.spot.rackspace.com/
name: example
contexts:
- context:
        cluster: example
        namespace: default
        user: ngpc-user
name: rxtspot-example
current-context: rxtspot-example
kind: Config
preferences: {}
users:
- name: ngpc-user
user:
        token: >-
        ey..........MySuperLongTokenStringIRedacted............zg
```

Note that the provider
- outputs the server url information successfully
- does not properly indent the multiline text fields `.users[0].user.token` and `.clusters[0].cluster.server`
- does not properly indent `.users[0].user`
- does not properly indent  `.contexts[0].name`
- does not properly indent `.users[0].user`

# Expected Behavior

- kubeconfig should be functional with all required data to connect to a cloudspace.
- kubeconfig should be correctly formatted.
- the `spot_cloudspace` data resource should allow the user to optionally toggle the resource to wait until the cloudspace is provisioned before moving on.

# Workaround

Use the shell provider to write the kubeconfig from currently available data values.

shell/manipulate_kubeconfig/create.sh

```bash
cat <<EOF > $KUBECONFIG_PATH
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://$SERVER
  name: $NAME
contexts:
- context:
    cluster: $NAME
    namespace: default
    user: ngpc-user
  name: $NAME
- context:
    cluster: $NAME
    namespace: default
    user: oidc
  name: $NAME-oidc
current-context: $NAME
kind: Config
preferences: {}
users:
- name: ngpc-user
  user:
    token: $TOKEN
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://login.spot.rackspace.com/
      - --oidc-client-id=mwG3lUMV8KyeMqHe4fJ5Bb3nM1vBvRNa
      - --oidc-extra-scope=openid
      - --oidc-extra-scope=profile
      - --oidc-extra-scope=email
      - --oidc-auth-request-extra-params=organization=$ORG_ID
      - --token-cache-dir=~/.kube/cache/oidc-login/$ORG_ID
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
EOF

cat <<EOF
{
    "path": "$KUBECONFIG_PATH",
    "md5": "$(sha3sum $KUBECONFIG_PATH | awk '{print $1}')"
}
EOF
```

shell/manipulate_kubeconfig/delete.sh

```bash
rm -f $KUBECONFIG_PATH
```

cloudspace.tf

```terraform
terraform {
    backend "s3" {
        region = "us-east-2"
        bucket = "open-tofu-remote"
        key = "rackspace-spot/argocd/terraform.tfstate"
    }

    required_providers {
        shell = {
          source = "scottwinkler/shell"
          version = "1.7.10"
        }

        spot = {
            source = "rackerlabs/spot"
            version = "0.0.3"
        }
    }
}

provider "shell" {
    environment = {}
    sensitive_environment = {}
    interpreter = ["/bin/sh", "-c"]
    enable_parallelism = false
}

provider "spot" {}

resource "spot_cloudspace" "cloudspace" {
  cloudspace_name    = "example"
  region             = "us-central-dfw-1"
  hacontrol_plane    = false
}

resource "spot_spotnodepool" "example" {
  cloudspace_name = "example"
  server_class    = "mh.vs1.2xlarge-dfw"
  bid_price       = 0.03
  autoscaling = {
    min_nodes = 2
    max_nodes = 4
  }
}

data "spot_cloudspace" "cloudspace" {
  id = spot_cloudspace.cloudspace.id
}

# resource "local_sensitive_file" "home_kubeconfig" {
#   content  = data.spot_cloudspace.cloudspace.kubeconfig
#   filename = pathexpand("~/.kube/${data.spot_cloudspace.cloudspace.id}-kubeconfig.yaml")
# }

resource "shell_script" "kubeconfig" {
    lifecycle_commands {
        //I suggest having these command be as separate files if they are non-trivial
        create = file("${path.module}/shell/manipulate_kubeconfig/create.sh")
        # read   = file("${path.module}/shell/manipulate_kubeconfig/read.sh")
        update = file("${path.module}/shell/manipulate_kubeconfig/create.sh")
        delete = file("${path.module}/shell/manipulate_kubeconfig/delete.sh")
    }

    environment = {
        //changes to one of these will trigger an update
        KUBECONFIG_PATH = pathexpand("~/.kube/${data.spot_cloudspace.cloudspace.id}-kubeconfig.yaml")
        ORG_ID = replace(split("/", data.spot_cloudspace.cloudspace.id)[0], "-", "_")
        NAME = split("/", data.spot_cloudspace.cloudspace.id)[1]
    }


    //sensitive environment variables are exactly the
    //same as environment variables except they don't
    //show up in log files
    sensitive_environment = {
        SERVER = data.spot_cloudspace.cloudspace.api_server_endpoint
        TOKEN  = data.spot_cloudspace.cloudspace.token
    }

    //sets current working directory
    working_directory = path.module

    //triggers a force new update if value changes, like null_resource
    triggers = {
        when_server_changed = data.spot_cloudspace.cloudspace.api_server_endpoint
        when_token_changed = data.spot_cloudspace.cloudspace.token
    }
}
```

**Comment by MarcPerezPro** [comment]
In my case it did output the server information with the valid server URL:
```yaml
apiVersion: v1
clusters:
- cluster:
	insecure-skip-tls-verify: true
	server: >-
	https://REDACTED.spot.rackspace.com/
name: us-central-ord-1
contexts:
- context:
	cluster: us-central-ord-1
	namespace: default
	user: ngpc-user
name: rxtspot-us-central-ord-1
current-context: rxtspot-us-central-ord-1
kind: Config
preferences: {}
users:
- name: ngpc-user
user:
	token: >-
	REDACTED

```
It didn't output the OIDC config, but I only care about programmatic access.
